### ISSUE TITLE
IMU not working "GetIMUValueBuffer failed"

### ISSUE THREAD

**Issue by martimorta-at-work** [i3drobotics/deimos-ros#14]
Hi,
there has been this problem with the IMU since I have been using the camera, I have been just commenting it but it's time to understand the problem.
I am running the camera in ubuntu 16.04 and ROS Kinetic, the udev rule is copied and still, this error appears with high frequency in the terminal, and obviously, the imu topic publishes nothing but empty messages:

```
GetIMUValueBuffer failed
ControlIMUCapture: IMU Disabled, Enable using SetIMUConfig
```

**Comment by jveitchmichaelis** [comment]
Do you get any errors when `deimosCamera::SetIMUConfigDefaultEnable()` is called? 

https://github.com/i3drobotics/i3dr_deimos-ros/blob/335c8ea1676f0b6eceb81a22729ad8921e8f7140/src/deimos_ros.cpp#L582

**Comment by martimorta-at-work** [comment]
Well, it seems to work now :confused:
 Anyway I would have a look at how the driver treats the imu failure, so at least it doesn't saturate the output with messages. Using ROS_ERROR_ONCE or ROS_ERROR_THROTTLE and [ROS logging](http://wiki.ros.org/roscpp/Overview/Logging) in general for the driver would be good too!
