### ISSUE TITLE
Building on the Jetson TX1

### ISSUE THREAD

**Issue by void-robotics** [i3drobotics/deimos-ros#2]
Hello, 

When building on the Jetson TX1, it throws this error:

```
In file included from /home/nvidia/[company]/src/(dependencies)/deimos-ros/include/uvc_camera/deimos_ros.h:3:0,
                 from /home/nvidia/[company]/src/(dependencies)/deimos-ros/src/deimos_node.cpp:4:
/home/nvidia/[company]/src/(dependencies)/deimos-ros/include/uvc_cam/uvc_cam.h:31:21: fatal error: libv4l2.h: No such file or directory
```

According to NVIDIA, the Tara camera should be able to run on the Jetson TX1.

Thanks,
Nathan

**Comment by jveitchmichaelis** [comment]
Hi,

The error isn't to do with this package. You're missing v4l2, or the compiler can't find it. Try:

`sudo apt-get install libv4l-dev v4l-utils qv4l2 v4l2ucp`

Cheers,
Josh

**Comment by nathangeorge1** [comment]
thanks now I get this:

```
In file included from /home/nvidia/MedAcuityRobotics/src/(dependencies)/see3cam/include/uvc_camera/tara_ros.h:3:0,
                 from /home/nvidia/MedAcuityRobotics/src/(dependencies)/see3cam/src/tara_node.cpp:4:
/home/nvidia/MedAcuityRobotics/src/(dependencies)/see3cam/include/uvc_cam/uvc_cam.h:41:28: fatal error: xunit_lib_tara.h: No such file or directory
```

**Comment by jveitchmichaelis** [comment]
This was fixed in: https://github.com/i3drobotics/deimos-ros/commit/cc5d488e50160d71b935a2819a3b65ac4aed57da

(Incidentally, the v4l dependency was also fixed in https://github.com/i3drobotics/deimos-ros/commit/ec2b6878508f2f5b4ceedac7580c3658377b0717)

I'd suggest trying this package rather than using `see3cam` directly, as we've already taken steps to fix most of the obvious install problems.

**Comment by void-robotics** [comment]
awesome; just got this package working; I also had to install

`sudo apt install ros-kinetic-joint-state-publisher ros-kinetic-stereo-image-proc ros-kinetic-robot-state-publisher ros-kinetic-xacro`

**Comment by void-robotics** [comment]
also it'd be helpful to include this install steps in the README, for others who want to install this

**Comment by jveitchmichaelis** [comment]
Glad to hear it worked, I've updated the docs and the package.xml so this should be easier using rosdep in future.
