### ISSUE TITLE
GetIMUValueBuffer: IMU Disabled, Enable using SetIMUConfig

### ISSUE THREAD

**Issue by void-robotics** [i3drobotics/deimos-ros#5]
Hello,

I get the following error:

```
GetIMUValueBuffer: IMU Disabled, Enable using SetIMUConfig
GetIMUValueBuffer failed
GetIMUValueBuffer: IMU Disabled, Enable using SetIMUConfig
GetIMUValueBuffer failed
GetIMUValueBuffer: IMU Disabled, Enable using SetIMUConfig
GetIMUValueBuffer failed
GetIMUValueBuffer: IMU Disabled, Enable using SetIMUConfig
GetIMUValueBuffer failed
GetIMUValueBuffer: IMU Disabled, Enable using SetIMUConfig
GetIMUValueBuffer failed
GetIMUValueBuffer: IMU Disabled, Enable using SetIMUConfig
```

How do I enable the IMU? I also could have a missing package but not sure which one.

Although I get:

```
$ rosdep install deimos
#All required rosdeps installed successfully
```

**Comment by jveitchmichaelis** [comment]
There are no external dependencies for the IMU. It's enabled by default during setup [here](https://github.com/i3drobotics/deimos-ros/blob/335c8ea1676f0b6eceb81a22729ad8921e8f7140/src/deimos_ros.cpp#L172). Control is done via the xunit library which should be built when you compile the node.

It's worth trying a different machine/port if possible (and the usual advice of turn it off and on again). It may be Linux being funny or a problem with your camera board. Occasionally we've seen boards refuse to respond to commands e.g. exposure control, but we've not been able to isolate the issue (both on Windows and Linux). They usually come back to life after a power cycle and possibly a machine reboot.

**Comment by void-robotics** [comment]
Power cycling, rebooting, or using a different port didn't work. It probably isn't a camera problem because it worked on Windows e-CAMView.

Any other ideas of how I can fix this?

**Comment by jveitchmichaelis** [comment]
Just a thought - have you installed the udev rule?

    sudo cp 99-uvc.rules /etc/udev/rules.d/
    sudo service udev restart

**Comment by void-robotics** [comment]
I agree; it's probably an issue with the hardware, as it throws a different error on Linux (see #6). I'll keep debugging the TX1

**Comment by jveitchmichaelis** [comment]
Apologies - I ninja edited there, do you have the udev rules installed?

**Comment by void-robotics** [comment]
I ran those 2 commands; but same error

**Comment by void-robotics** [comment]
actually after I did a clean build, it worked! not sure if it was the rules or the clean build but the camera is working now

**Comment by jveitchmichaelis** [comment]
Excellent, closing!

**Comment by void-robotics** [comment]
I suggest documenting this somewhere, likely the README Installation
